services:
  - type: web
    name: operacionbarco
    env: python
    rootDir: .
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn "app:create_app()"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.6
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
    plan: free